const jokes = [
  "Generating your commit message… please enjoy this joke while I pretend to work harder than you do.",
  "Still thinking… If this takes too long, feel free to blame latency, AI, your wifi, Mercury in retrograde, or JavaScript. They're all valid.",
  "Hold on… Currently negotiating with your code. It's resisting.",
  "Processing… Your commit message is loading. Unlike your tests, it *will* pass.",
  "Working… This would be faster, but your code started explaining itself. I had to stop it.",
  "One moment… Git says it refuses to take responsibility for this commit.",
  "Cooking up brilliance… If your code crashes after this, it's legally not my fault.",
  "Hang tight… I'm searching deep neural networks for words that won't embarrass Future You.",
  "Thinking… Your commit message is 90% done. The remaining 10% is emotional damage cleanup.",
  "Almost there… This commit message will be better than the commit itself. Sorry, I don't make the rules.",
  "Just a sec… Your code asked for a joke too, but I'm afraid it wouldn't understand it.",
  "Brewing… This commit message is being handcrafted by unpaid virtual interns.",
  "Optimizing… I tried to ask your last commit for context, but it ran away screaming.",
  "Stand by… Your commit message is being assembled by highly trained raccoons.",
  "Loading creativity… If this message looks smart, remember: you didn't write it.",
  "Hold tight… Your code is throwing exceptions at me. I'm throwing them back.",
  "Analyzing… Your commit history is chaotic neutral.",
  "Please wait… Attempting to make sense of your diffs. Send snacks.",
  "Thinking hard… Your code said it wanted to remain undocumented. I insisted.",
  "Loading… Your commit message is stuck in traffic behind a million npm packages.",
  "Processing… I ran your code in my head. It segfaulted my imagination.",
  "Calculating… Your codebase asked for a therapist. I referred it to Stack Overflow.",
  "Summoning creativity… If I generate a great commit message, will you promise not to squash it into 'fix stuff'?",
  "Preparing brilliance… I've seen cleaner merge conflicts in soap operas.",
  "Working on it… Your repo whispered: 'please stop pushing directly to main'.",
  "Generating… If your code were a person, it would definitely ignore the README.",
  "Recovering… Your tests failed so hard they apologized.",
  "Waking up… I asked Git for help; it responded with a shrug.",
  "Crunching bits… Your code is like an onion. Every layer makes me cry.",
  "Polishing… This commit message will age better than most of your TODOs.",
];

export const getRandomJoke = () => {
  return jokes[Math.floor(Math.random() * jokes.length)];
};
