import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { PROVIDERS } from "@/llm/provider";
import { getLiveProviderModels } from "@/misc/model-status";

const CUSTOM_OPENAI_FALLBACK_MODELS = ["gpt-4o", "gpt-4o-mini"];

async function main() {
  const liveModels = await getLiveProviderModels(true);

  const providerModels: Record<string, string[]> = {};
  for (const p of PROVIDERS) {
    if (p === "Custom OpenAI Based Provider") {
      providerModels[p] = CUSTOM_OPENAI_FALLBACK_MODELS;
    } else if (p === "OpenRouter") {
      providerModels[p] = ["openrouter/auto"];
    } else {
      providerModels[p] = liveModels[p] ?? [];
    }
  }

  const outPath = join(process.cwd(), "src", "llm", "models.ts");
  const content = `import type { GcmgProviders } from "./provider";

// Auto-generated by scripts/generate-models.ts - do not edit manually
// Regenerated: ${new Date().toISOString()}

export const PROVIDER_MODELS: Record<GcmgProviders, string[]> = ${JSON.stringify(providerModels, null, 2)};
`;

  writeFileSync(outPath, content, "utf-8");
  console.log(`Wrote ${outPath}`);
  for (const [k, v] of Object.entries(providerModels)) {
    console.log(`  ${k}: ${Array.isArray(v) ? v.length : 0} models`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
