import axios from "axios";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { PROVIDERS } from "@/llm/provider";

type OpenRouterModel = {
  id: string;
};

const CUSTOM_OPENAI_FALLBACK_MODELS = ["gpt-4o", "gpt-4o-mini"];

async function main() {
  const openRouterModels: OpenRouterModel[] = (
    await axios.get("https://openrouter.ai/api/v1/models")
  ).data.data;

  const modelsByLower = new Map<string, string[]>();
  const providerSet = new Set(PROVIDERS.map((p) => p.toLowerCase()));

  for (const model of openRouterModels) {
    // eg. openai/gpt-4o:free
    let [provider, modelId] = model.id.split("/");
    provider = provider.toLowerCase() ?? "";
    modelId = modelId.split(":")[0] ?? "";

    if (modelId.includes("image")) {
      continue;
    }

    if (!providerSet.has(provider) || !modelId) continue;

    const list = modelsByLower.get(provider) ?? [];
    list.push(modelId.trim());
    modelsByLower.set(provider, list);
  }

  const providerModels: Record<string, string[]> = {};
  for (const p of PROVIDERS) {
    const key = p.toLowerCase();
    if (p === "Custom OpenAI Based Provider") {
      providerModels[p] =
        (modelsByLower.get(key)?.length ?? 0) > 0
          ? (modelsByLower.get(key) ?? [])
          : CUSTOM_OPENAI_FALLBACK_MODELS;
    } else {
      providerModels[p] = modelsByLower.get(key) ?? [];
    }
  }

  const outPath = join(process.cwd(), "src", "llm", "models.ts");
  const content = `import type { GcmgProviders } from "./provider";

// Auto-generated by scripts/generate-models.ts - do not edit manually

export const PROVIDER_MODELS: Record<GcmgProviders, string[]> = ${JSON.stringify(providerModels, null, 2)};
`;

  writeFileSync(outPath, content, "utf-8");
  console.log(`Wrote ${outPath}`);
}
main();
